name: .NET CI/CD with Code Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 5.0 (o .NET 6.0 si decides actualizar)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore ./tarjeta/tarjeta.sln

    - name: Build
      run: dotnet build --no-restore ./tarjeta/tarjeta.sln

    - name: Run tests with coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage" ./tarjeta/tarjeta.sln

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./tarjeta/coverage.cobertura.xml  # Ajusta esta ruta según la ubicación exacta del archivo
